"""Pydantic schemas for API request/response validation"""

# Authentication & User schemas
from app.schemas.auth import (
    UserRegister,
    UserLogin,
    Token,
    TokenData,
    UserResponse,
    UserUpdate,
    PasswordChange,
)

# Keyword schemas
from app.schemas.keyword import (
    KeywordBase,
    KeywordCreate,
    KeywordUpdate,
    KeywordResponse,
    KeywordWithScores,
)

# GEOINT schemas
from app.schemas.geoint import (
    RegionTypeEnum,
    BudgetRecommendationRequest,
    KeywordAnalysisRequest,
    GEOINTScoreResponse,
    TopRegionResponse,
    BudgetAllocation,
    HeatmapMetadata,
    HeatmapResponse,
    TrendMetrics,
    RegionInterest,
    KeywordAnalysisResponse,
    AdPerformanceMetrics,
    GoogleAdsKeywordMetrics,
    AdRecommendation,
)

# Strategy schemas
from app.schemas.strategy import (
    StrategyStatusEnum,
    TaskStatusEnum,
    TaskPriorityEnum,
    StrategyCreate,
    StrategyUpdate,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    WeekResponse,
    StrategyResponse,
    StrategyWithWeeks,
    StrategyGenerationRequest,
)

# Competitor schemas
from app.schemas.competitor import (
    CompetitorCreate,
    CompetitorUpdate,
    CompetitorAnalyzeRequest,
    CompetitorCompareRequest,
    AIInsightsRequest,
    CompetitorResponse,
    CompetitorSnapshotResponse,
    CompetitorWithSnapshots,
    CompetitorKeywordOverlap,
    CompetitorGapAnalysis,
    CompetitorComparison,
    CompetitorInsights,
    CompetitorTrendPoint,
    CompetitorTrendsResponse,
    BacklinkResponse,
    BacklinkProfileResponse,
    ContentGapItem,
    ContentGapResponse,
    AdIntelligenceResponse,
    TechStackResponse,
    MarketOverviewResponse,
    CompetitorComparisonResponse,
)

# Media schemas
from app.schemas.media import (
    SentimentEnum,
    PROutcomeEnum,
    MediaMentionCreate,
    MediaMentionUpdate,
    MediaMentionResponse,
    MediaMentionSearchRequest,
    PROpportunityCreate,
    PROpportunityUpdate,
    PROpportunityResponse,
    MediaAnalytics,
    PRPerformance,
)

# Dashboard schemas
from app.schemas.dashboard import (
    ActivityType,
    DashboardStats,
    TrendDataPoint,
    GEOINTTrendResponse,
    KeywordPerformanceItem,
    KeywordPerformanceResponse,
    RegionDistributionItem,
    RegionalDistributionResponse,
    StrategyProgressItem,
    StrategyProgressResponse,
    ActivityItem,
    ActivitiesResponse,
    DashboardOverview,
)

# Agent schemas
from app.schemas.agent import (
    AgentTool,
    AgentAction,
    AgentContext,
    AgentChatRequest,
    AgentChatResponse,
    AGENT_TOOLS,
    QUICK_ACTIONS_BY_PAGE,
)

__all__ = [
    # Auth
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenData",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    # Keywords
    "KeywordBase",
    "KeywordCreate",
    "KeywordUpdate",
    "KeywordResponse",
    "KeywordWithScores",
    # GEOINT
    "RegionTypeEnum",
    "BudgetRecommendationRequest",
    "KeywordAnalysisRequest",
    "GEOINTScoreResponse",
    "TopRegionResponse",
    "BudgetAllocation",
    "HeatmapMetadata",
    "HeatmapResponse",
    "TrendMetrics",
    "RegionInterest",
    "KeywordAnalysisResponse",
    "AdPerformanceMetrics",
    "GoogleAdsKeywordMetrics",
    "AdRecommendation",
    # Strategy
    "StrategyStatusEnum",
    "TaskStatusEnum",
    "TaskPriorityEnum",
    "StrategyCreate",
    "StrategyUpdate",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "WeekResponse",
    "StrategyResponse",
    "StrategyWithWeeks",
    "StrategyGenerationRequest",
    # Competitors
    "CompetitorCreate",
    "CompetitorUpdate",
    "CompetitorAnalyzeRequest",
    "CompetitorCompareRequest",
    "AIInsightsRequest",
    "CompetitorResponse",
    "CompetitorSnapshotResponse",
    "CompetitorWithSnapshots",
    "CompetitorKeywordOverlap",
    "CompetitorGapAnalysis",
    "CompetitorComparison",
    "CompetitorInsights",
    "CompetitorTrendPoint",
    "CompetitorTrendsResponse",
    "BacklinkResponse",
    "BacklinkProfileResponse",
    "ContentGapItem",
    "ContentGapResponse",
    "AdIntelligenceResponse",
    "TechStackResponse",
    "MarketOverviewResponse",
    "CompetitorComparisonResponse",
    # Media
    "SentimentEnum",
    "PROutcomeEnum",
    "MediaMentionCreate",
    "MediaMentionUpdate",
    "MediaMentionResponse",
    "MediaMentionSearchRequest",
    "PROpportunityCreate",
    "PROpportunityUpdate",
    "PROpportunityResponse",
    "MediaAnalytics",
    "PRPerformance",
    # Dashboard
    "ActivityType",
    "DashboardStats",
    "TrendDataPoint",
    "GEOINTTrendResponse",
    "KeywordPerformanceItem",
    "KeywordPerformanceResponse",
    "RegionDistributionItem",
    "RegionalDistributionResponse",
    "StrategyProgressItem",
    "StrategyProgressResponse",
    "ActivityItem",
    "ActivitiesResponse",
    "DashboardOverview",
    # Agent
    "AgentTool",
    "AgentAction",
    "AgentContext",
    "AgentChatRequest",
    "AgentChatResponse",
    "AGENT_TOOLS",
    "QUICK_ACTIONS_BY_PAGE",
]
